parameters:
  version: '%env(default:versionDefault:ROOTER_VERSION)%'
  versionDefault: '@@latest'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      string $version: '%version%'

  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: ['command']

  RunAsRoot\Rooter\:
    resource: '%rooter.dir%/src'

  RunAsRoot\Rooter\CliApplication:
    public: true
    arguments:
      - !tagged command

  Twig\Loader\FilesystemLoader:
    arguments:
      - '%rooter.dir%/templates'
  Twig\Environment:
    arguments:
      - '@Twig\Loader\FilesystemLoader'

  Symfony\Component\Console\Formatter\OutputFormatter:
    arguments:
      $styles: {
        title: '@RunAsRoot\Rooter\Cli\Output\Style\TitleOutputStyle'
      }
